# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [4]:
import numpy as np

# formula = weight / (height**2) * 730

height = np.array([69, 70, 71, 72, 73, 74, 75])
weight = np.array([110, 120, 130, 140, 150, 160, 170])

bmi = weight / (height**2) * 730

for h, w, b in zip(height, weight, bmi):
    print(f"Height: {h}, weight: {w} lb, BMI: {b:.2f}")



Height: 69, weight: 110 lb, BMI: 16.87
Height: 70, weight: 120 lb, BMI: 17.88
Height: 71, weight: 130 lb, BMI: 18.83
Height: 72, weight: 140 lb, BMI: 19.71
Height: 73, weight: 150 lb, BMI: 20.55
Height: 74, weight: 160 lb, BMI: 21.33
Height: 75, weight: 170 lb, BMI: 22.06


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [16]:
import numpy as np

def generate_matrix(rows, columns, datatype='float', low=0, high=1):
    if data_type not in ('int', 'float'):
        raise ValueError("El tipo de datos debe ser 'int' o 'float'.")

    if data_type == 'int':
        matrix = np.random.randint(low, high + 1, size=(rows, columns))
    else:
        matrix = np.random.uniform(low, high, size=(rows, columns))

    return matrix

rows = 8
colums = 8
data_type = 'int' 
low = 0
high = 0

random_matrix = generate_matrix(rows, colums, data_type, low, high)
print(random_matrix)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [4]:
import csv
import numpy as np

FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

data_2017 = np.loadtxt('redsox_2017_hitting.txt', delimiter=',', skiprows=1, usecols=(3,))
data_2018 = np.loadtxt('redsox_2018_hitting.txt', delimiter=',', skiprows=1, usecols=(3,))
slg_diff = np.mean(data_2018) - np.mean(data_2017)

better_year = "2018" if slg_diff > 0 else "2017"

print("Based on SLG, the better year was:", better_year)

Based on SLG, the better year was: 2018
